import type { Location } from "@/schemas/zodSchema";

// A mock row shaped like what Supabase returns from the locations + location_hours join.
export const mockDbRow = {
  id: 'test-uuid-123',
  name: 'Test Food Bank',
  address: '123 Main St',
  address2: null,
  city: 'Portland',
  state: 'OR',
  zip_code: '97201',
  zip: null,
  latitude: 45.523,
  longitude: -122.6765,
  offer_desc: 'Free meals',
  offer_source: 'https://example.com',
  website: null,
  donation_link: null,
  delivery_available: false,
  volunteer_link: null,
  phone: '503-555-1234',
  info_last_verified: '2025-01-01',
  updated_at: '2025-01-01',
  description: null,
  is_active: true,
  created_at: '2025-01-01',
  created_by: null,
  neighborhood: null,
  verified_at: null,
  verification_status: 'pending',
  owner_claimed: null,
  owner_verified_at: null,
  location_hours: [
    {
      id: 'hours-uuid-123',
      location_id: 'test-uuid-123',
      day: 'monday' as const,
      opens_at: '08:00:00',
      closes_at: '17:00:00',
      notes: null,
    },
  ],
};

export const mockHours: Location['hours'] = {
  monday: [{ start: '08:00', end: '17:00' }],
  tuesday: [],
  wednesday: [],
  thursday: [],
  friday: [],
  saturday: [],
  sunday: [],
};

export const mockLocation: Location = {
  id: 'test-uuid-123',
  name: 'Test Food Bank',
  address: '123 Main St',
  city: 'Portland',
  state: 'OR',
  zipCode: '97201',
  latitude: 45.523,
  longitude: -122.6765,
  offerDesc: 'Free meals for families',
  offerSource: 'https://example.com',
  deliveryAvailable: false,
  phoneNumber: '503-555-1234',
  hours: mockHours,
  infoLastVerified: '2025-01-01',
  lastUpdated: '2025-01-01',
  verificationStatus: 'pending',
};
