import type { DayOfWeek } from '@/types/utils';

export const DAYS: DayOfWeek[] = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];

export const DAY_LABELS: Record<DayOfWeek, string> = {
  monday: 'Monday',
  tuesday: 'Tuesday',
  wednesday: 'Wednesday',
  thursday: 'Thursday',
  friday: 'Friday',
  saturday: 'Saturday',
  sunday: 'Sunday',
};

export const VENUE_TYPE_LABELS: Record<string, string> = {
  food_pantry: 'Food Pantry',
  food_bank: 'Food Bank',
  restaurant: 'Restaurant',
  cafe: 'Cafe',
  grocery_store: 'Grocery Store',
  farmers_market: 'Farmers Market',
  community_organization: 'Community Organization',
  other: 'Other',
};

export const PRICE_TYPE_LABELS: Record<string, string> = {
  free: 'Free',
  discount: 'Discount',
};

export const ELIGIBILITY_TYPE_LABELS: Record<string, string> = {
  anyone: 'Anyone',
  student: 'Student',
  senior: 'Senior',
  kids: 'Kids',
  military: 'Military',
  snap: 'SNAP',
  income_requirement: 'Income Requirement',
  other: 'Other',
};

export const FOOD_FORMAT_LABELS: Record<string, string> = {
  dine_in: 'Dine-in',
  grocery: 'Groceries',
  pickup: 'Pickup',
  delivery: 'Delivery',
};

export const APP_NAME = 'Rose City Finds';
export const CONTACT_EMAIL = 'rosecityfinds.info@gmail.com';

export const SITE_TITLE = 'Create Next App';
export const SITE_DESCRIPTION = 'Generated by create next app';

export const FILTER_CHIPS = [
  { key: 'price', value: 'free', label: 'Free' },
  { key: 'price', value: 'discount', label: 'Discount' },
  { key: 'foodType', value: 'prepared', label: 'Prepared' },
  { key: 'foodType', value: 'groceries', label: 'Groceries' },
  { key: 'foodType', value: 'restaurant', label: 'Restaurant' },
  { key: 'accessType', value: 'pickup', label: 'Pickup' },
  { key: 'accessType', value: 'delivery', label: 'Delivery' },
  { key: 'eligibility', value: 'anyone', label: 'Anyone' },
] as const;

export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  RESULTS: '/results',
  RESULTS_OPEN_NOW: '/results?openNow=true',
} as const;

export const API_ROUTES = {
  LOCATIONS: '/api/locations',
  AUTH_SIGNIN: '/api/auth/signin',
  AUTH_SIGNOUT: '/api/auth/signout',
  AUTH_RESET_PASSWORD: '/api/auth/reset-password',
  AUTH_UPDATE_PASSWORD: '/api/auth/update-password',
} as const;
