import type { DayOfWeek } from '@/types/utils';

export const DAYS: DayOfWeek[] = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];

export const APP_NAME = 'Rose City Finds';
export const CONTACT_EMAIL = 'rosecityfinds.info@gmail.com';

export const SITE_TITLE = 'Create Next App';
export const SITE_DESCRIPTION = 'Generated by create next app';

export const FILTER_CHIPS = [
  { key: 'price', value: 'free', label: 'Free' },
  { key: 'price', value: 'discount', label: 'Discount' },
  { key: 'foodType', value: 'prepared', label: 'Prepared' },
  { key: 'foodType', value: 'groceries', label: 'Groceries' },
  { key: 'foodType', value: 'restaurant', label: 'Restaurant' },
  { key: 'accessType', value: 'pickup', label: 'Pickup' },
  { key: 'accessType', value: 'delivery', label: 'Delivery' },
] as const;

export const ROUTES = {
  HOME: '/',
  AUTH: '/auth',
  MAP: '/map',
  MAP_OPEN_NOW: '/map?openNow=true',
} as const;

export const API_ROUTES = {
  LOCATIONS: '/api/locations',
  AUTH_SIGNIN: '/api/auth/signin',
  AUTH_SIGNOUT: '/api/auth/signout',
  AUTH_RESET_PASSWORD: '/api/auth/reset-password',
  AUTH_UPDATE_PASSWORD: '/api/auth/update-password',
} as const;
