import { describe, it, expect, vi, beforeEach } from 'vitest'

const mockReadFileSync = vi.fn()
const mockWriteFileSync = vi.fn()

vi.mock('node:fs', () => {
  const readFileSync = (...args) => mockReadFileSync(...args)
  const writeFileSync = (...args) => mockWriteFileSync(...args)
  return { readFileSync, writeFileSync, default: { readFileSync, writeFileSync } }
})

const { main } = await import('../../scripts/generate-bulk-seed.mjs')

const BEGIN_MARKER = '-- BEGIN FAKER BULK SEED (generated by scripts/generate-bulk-seed.mjs)'
const END_MARKER = '-- END FAKER BULK SEED'

beforeEach(() => {
  vi.clearAllMocks()
})

describe('generate-bulk-seed main()', () => {
  it('writes a block containing all six INSERT statements', () => {
    mockReadFileSync.mockReturnValue('-- hand-written fixtures\n')
    main()

    expect(mockWriteFileSync).toHaveBeenCalledTimes(1)
    const written = mockWriteFileSync.mock.calls[0][1]
    expect(written).toContain('INSERT INTO public.businesses')
    expect(written).toContain('INSERT INTO public.locations')
    expect(written).toContain('INSERT INTO public.offers')
    expect(written).toContain('INSERT INTO public.offer_locations')
    expect(written).toContain('INSERT INTO public.location_hours')
    expect(written).toContain('INSERT INTO public.offer_hours')
    expect(written).toContain('INSERT INTO public.verification_events')
  })

  it('wraps the generated block in the begin/end markers', () => {
    mockReadFileSync.mockReturnValue('-- hand-written fixtures\n')
    main()

    const written = mockWriteFileSync.mock.calls[0][1]
    expect(written).toContain(BEGIN_MARKER)
    expect(written).toContain(END_MARKER)
    expect(written.indexOf(BEGIN_MARKER)).toBeLessThan(written.indexOf(END_MARKER))
  })

  it('preserves hand-written content when no prior generated block exists', () => {
    mockReadFileSync.mockReturnValue('-- hand-written fixtures\n')
    main()

    const written = mockWriteFileSync.mock.calls[0][1]
    expect(written).toContain('-- hand-written fixtures')
    expect(written.indexOf('-- hand-written fixtures')).toBeLessThan(written.indexOf(BEGIN_MARKER))
  })

  it('replaces an existing generated block rather than duplicating it', () => {
    const priorContent =
      '-- hand-written fixtures\n\n' +
      `${BEGIN_MARKER}\n-- stale content\nINSERT INTO public.businesses (id) VALUES ('stale');\n${END_MARKER}\n`
    mockReadFileSync.mockReturnValue(priorContent)
    main()

    const written = mockWriteFileSync.mock.calls[0][1]
    expect(written).not.toContain('stale')
    expect(written.match(new RegExp(BEGIN_MARKER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g'))).toHaveLength(1)
    expect(written).toContain('-- hand-written fixtures')
  })

  it('reads from and writes to the seed.sql path', () => {
    mockReadFileSync.mockReturnValue('')
    main()

    expect(mockReadFileSync.mock.calls[0][0].pathname).toMatch(/supabase\/seed\.sql$/)
    expect(mockWriteFileSync.mock.calls[0][0].pathname).toMatch(/supabase\/seed\.sql$/)
  })

  it('logs a summary of what was generated', () => {
    mockReadFileSync.mockReturnValue('')
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {})
    main()
    expect(logSpy).toHaveBeenCalledWith(expect.stringContaining('businesses'))
    logSpy.mockRestore()
  })
})
